language: node_js
node_js:
  - "stable"
branches:
  only:
  - master
install:
  - npm install
  - npm install --only=dev
after_success:
  - npm run build:prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist/raabit-next/
  keep-history: true
  on:
    branch: master
notifications:
  email: false